string_to_boolean (_) accept
string_to_number (_) accept
string_to_object (_) accept
special_to_boolean (_) accept
special_to_number (_) accept
special_to_object (_) accept
special_to_string (_) accept
fixnum_to_string (_) accept
fixnum_to_boolean (_) accept
fixnum_to_object (_) accept
flonum_to_string (_) accept
flonum_to_boolean (_) accept
flonum_to_object (_) accept
number_to_string (_) accept
object_to_string (_) accept
object_to_boolean (_) accept
object_to_number (_) accept
object_to_primitive (_,-) accept
to_string (_) accept
to_boolean (_) accept
to_number (_) accept
to_object (_) accept
to_double (_) accept
special_to_double (_) accept
number_to_cint (_) accept
number_to_double (_) accept
to_cint (_) accept