string_to_boolean (_) accept
string_to_number (_) accept
string_to_object (_) unspecified
special_to_boolean (_) accept
special_to_number (_) accept
special_to_object (_) unspecified
special_to_string (_) accept
fixnum_to_string (_) accept
fixnum_to_boolean (_) unspecified
fixnum_to_object (_) unspecified
flonum_to_string (_) accept
flonum_to_boolean (_) unspecified
flonum_to_object (_) unspecified
number_to_string (_) accept
object_to_string (_) accept
object_to_boolean (_) unspecified
object_to_number (_) unspecified
object_to_primitive (_,-) accept
to_string (_) accept
to_boolean (_) accept
to_number (_) accept
to_object (_) unspecified
to_double (_) accept
special_to_double (_) unspecified
number_to_cint (_) accept
number_to_double (_) accept
to_cint (_) unspecified