add (-,_,_) accept
bitand (-,_,_) accept
bitor (-,_,_) accept
call (_,-) accept
div (-,_,_) accept
eq (-,_,_) accept
equal (-,_,_) accept
getprop (-,_,-) accept
leftshift (-,_,_) accept
lessthan (-,_,_) accept
lessthanequal (-,_,_) accept
mod (-,_,_) accept
mul (-,_,_) accept
new (-,_) accept
rightshift (-,_,_) accept
setprop (_,-,-) accept
sub (-,_,_) accept
tailcall (_,-) accept
unsignedrightshift (-,_,_) accept
