add (-,fixnum,fixnum) accept
add (-,string,string) accept
add (-,_,_) error
bitand (-,_,_) error
bitor (-,_,_) error
call (_,-) accept
div (-,_,_) error
eq (-,_,_) error
equal (-,fixnum,fixnum) accept
equal (-,_,_) error
getprop (-,array,-) accept
getprop (-,fixnum,-) accept
getprop (-,number_object,-) accept
getprop (-,_,-) error
leftshift (-,_,_) error
lessthan (-,fixnum,fixnum) accept
lessthan (-,_,_) error
lessthanequal (-,_,_) error
mod (-,_,_) error
mul (-,_,_) error
new (-,_) error
rightshift (-,fixnum,fixnum) accept
rightshift (-,_,_) error
setprop (array,-,-) accept
setprop (_,-,-) error
sub (-,fixnum,fixnum) accept
sub (-,_,_) error
tailcall (_,-) error
unsignedrightshift (-,_,_) error

