add (-,_,_) accept
bitand (-,_,_) accept
bitor (-,_,_) accept
call (_,-) accept
div (-,_,_) accept
eq (-,_,_) accept
equal (-,_,_) accept
getprop (-,_,_) accept
leftshift (-,_,_) accept
lessthan (-,_,_) accept
lessthanequal (-,_,_) accept
mod (-,_,_) accept
mul (-,_,_) accept
new (-,_) accept
rightshift (-,_,_) accept
setprop (_,_,_) accept
sub (-,_,_) accept
tailcall (_,-) accept
unsignedrightshift (-,_,_) accept
error (-,-) accept
fixnum (-,-) accept
geta (-) accept
getarg (-,-,-) accept
geterr (-) accept
getglobal (-,_) accept
getglobalobj (-) accept
getlocal (-,-,-) accept
instanceof (-,_,_) accept
isobject (-,_) accept
isundef (-,_) accept
jump (-) accept
jumpfalse (_,-) accept
jumptrue (_,-) accept
localcall (-) accept
makeclosure (-,-) accept
makeiterator (-,_) accept
move (-,_) accept
newframe (-,-) accept
nextpropnameidx (-,_) accept
not (-,_) accept
number (-,-) accept
pushhandler (-) accept
seta (_) accept
setarg (-,-,_) accept
setarray (_,-,_) accept
setfl (-) accept
setglobal (_,_) accept
setlocal (-,-,_) accept
specconst (-,-) accept
typeof (-,-) accept
end () accept
localret () accept
nop () accept
pophandler () accept
poplocal () accept
ret () accept
throw () accept
unknown () accept
